php:
  dockerfile: php-Dockerfile
  build: .
  environment:
    XDEBUG_CONFIG: remote_host=172.17.0.1
  links:
    - mysql
  ports:
    - 80:80
  volumes:
    - ./app/www:/var/www/html
node:
  dockerfile: node-Dockerfile
  build: .
  ports:
    - 35729:35729
  volumes:
    - .:/usr/src/app/app
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8080:80
    links:
        - mysql
    environment:
        PMA_HOST: mysql
mysql:
  image: mysql:5.5
  volumes_from:
    - data
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: project
    MYSQL_USER: project
    MYSQL_PASSWORD: project
data:
    image: mysql:5.5
    volumes:
        - /var/lib/mysql
    command: "true"
